import { Router, type Request, type Response } from "express";
import { pool } from "@workspace/db";
import crypto from "crypto";
import {
  isGoogleConfigured,
  generateAuthUrl,
  getTokensFromCode,
  getAccounts,
  getLocations,
  getLocationReviews,
  syncAll,
  getGBPStatus,
  getPerformance,
  publishGBPPost,
  replyToReview,
  generateAIReply,
  getValidToken,
  encryptToken,
} from "../services/google-service.js";
import { store } from "../services/store.js";
import { logger } from "../lib/logger.js";

const ORG_ID = "default";

// ── Server-side OAuth state store ─────────────────────────────────────────────
// States are generated by authenticated connect/start endpoints and consumed
// exactly once by the public callback. Each state expires after 10 minutes.

const OAUTH_STATE_TTL_MS = 10 * 60 * 1000;

const pendingOAuthStates = new Map<string, number>(); // state → expiry timestamp

function registerOAuthState(state: string): void {
  pendingOAuthStates.set(state, Date.now() + OAUTH_STATE_TTL_MS);
  // Prune expired states to prevent unbounded growth
  for (const [s, exp] of pendingOAuthStates) {
    if (Date.now() > exp) pendingOAuthStates.delete(s);
  }
}

function consumeOAuthState(state: string): boolean {
  const exp = pendingOAuthStates.get(state);
  if (exp === undefined) return false;
  pendingOAuthStates.delete(state);
  return Date.now() <= exp;
}

// ── Public router — OAuth callbacks only ──────────────────────────────────────
// These two routes must remain unauthenticated because Google redirects to them
// without our Bearer token. All other /google/* routes are protected below.

export const googlePublicRouter = Router();

googlePublicRouter.get("/google/callback", async (req: Request, res: Response) => {
  const { code, state, error: oauthError } = req.query as {
    code?: string;
    state?: string;
    error?: string;
  };

  if (oauthError) {
    res.redirect(`/?gbp_error=${encodeURIComponent(oauthError)}`);
    return;
  }
  if (!code) {
    res.status(400).json({ ok: false, error: "Missing OAuth code" });
    return;
  }

  // Validate that this state was generated by an authenticated session on this server
  if (!state || !consumeOAuthState(state)) {
    logger.warn("[GBP] OAuth callback rejected — invalid or expired state");
    res.status(400).json({ ok: false, error: "Invalid or expired OAuth state" });
    return;
  }

  try {
    const tokens = await getTokensFromCode(code);
    if (!tokens.access_token) throw new Error("No access token received");

    const userInfo = await fetch("https://www.googleapis.com/oauth2/v3/userinfo", {
      headers: { Authorization: `Bearer ${tokens.access_token}` },
    }).then(r => r.json()) as { sub?: string; email?: string };

    const client = await pool.connect();
    try {
      await client.query(
        `INSERT INTO google_accounts (id, org_id, google_id, email, access_token, refresh_token, token_expiry, scopes, connected_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,now())
         ON CONFLICT (org_id) DO UPDATE SET
           google_id=$3, email=$4, access_token=$5,
           refresh_token=COALESCE($6, google_accounts.refresh_token),
           token_expiry=$7, scopes=$8, updated_at=now()`,
        [
          `ga_${ORG_ID}`,
          ORG_ID,
          userInfo.sub || "",
          userInfo.email || "",
          encryptToken(tokens.access_token),
          tokens.refresh_token ? encryptToken(tokens.refresh_token) : null,
          tokens.expiry_date ? new Date(tokens.expiry_date).toISOString() : null,
          JSON.stringify(tokens.scope?.split(" ") || []),
        ]
      );
    } finally {
      client.release();
    }

    store.logActivity({
      type: "team",
      label: `Google Business Profile connecté — ${userInfo.email || ""}`,
      targetType: "connector",
    });

    syncAll(ORG_ID).catch(e => logger.warn({ e }, "[GBP] Background sync failed"));

    const frontendUrl = process.env["FRONTEND_URL"] || "http://localhost:3000";
    res.redirect(`${frontendUrl}?gbp_connected=1`);
  } catch (e) {
    logger.error({ e }, "[GBP] OAuth callback failed");
    res.status(500).json({ ok: false, error: "OAuth exchange failed" });
  }
});

googlePublicRouter.get("/google/oauth/callback", async (req: Request, res: Response) => {
  const { code, state, error: oauthError } = req.query as {
    code?: string;
    state?: string;
    error?: string;
  };

  if (oauthError) {
    res.redirect(`/?gbp_error=${encodeURIComponent(oauthError)}`);
    return;
  }
  if (!code) {
    res.status(400).json({ ok: false, error: "Missing OAuth code" });
    return;
  }

  // Validate that this state was generated by an authenticated session on this server
  if (!state || !consumeOAuthState(state)) {
    logger.warn("[GBP] OAuth/callback rejected — invalid or expired state");
    res.status(400).json({ ok: false, error: "Invalid or expired OAuth state" });
    return;
  }

  try {
    const tokens = await getTokensFromCode(code);
    if (!tokens.access_token) throw new Error("No access token received");

    const userInfo = await fetch("https://www.googleapis.com/oauth2/v3/userinfo", {
      headers: { Authorization: `Bearer ${tokens.access_token}` },
    }).then(r => r.json()) as { sub?: string; email?: string };

    const client = await pool.connect();
    try {
      await client.query(
        `INSERT INTO google_accounts (id, org_id, google_id, email, access_token, refresh_token, token_expiry, scopes, connected_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,now())
         ON CONFLICT (org_id) DO UPDATE SET
           google_id=$3, email=$4, access_token=$5,
           refresh_token=COALESCE($6, google_accounts.refresh_token),
           token_expiry=$7, scopes=$8, updated_at=now()`,
        [
          `ga_${ORG_ID}`,
          ORG_ID,
          userInfo.sub || "",
          userInfo.email || "",
          encryptToken(tokens.access_token),
          tokens.refresh_token ? encryptToken(tokens.refresh_token) : null,
          tokens.expiry_date ? new Date(tokens.expiry_date).toISOString() : null,
          JSON.stringify(tokens.scope?.split(" ") || []),
        ]
      );
    } finally {
      client.release();
    }

    store.logActivity({
      type: "team",
      label: `GBP connecté — ${userInfo.email || ""}`,
      targetType: "connector",
    });

    syncAll(ORG_ID).catch(e => logger.warn({ e }, "[GBP] Background sync failed"));

    const frontendUrl = process.env["FRONTEND_URL"] || "https://app.flowpoint.pro";
    res.redirect(`${frontendUrl}?gbp_connected=1`);
  } catch (e) {
    logger.error({ e }, "[GBP] OAuth/callback failed");
    res.status(500).json({ ok: false, error: "OAuth exchange failed" });
  }
});

// ── Protected router — all management endpoints (requires auth) ───────────────
// Mounted after requireAuth in index.ts.

const router = Router();

router.get("/google/connect", (_req: Request, res: Response) => {
  if (!isGoogleConfigured()) {
    res.status(503).json({
      ok: false,
      error: "Google OAuth not configured. Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET to environment variables.",
    });
    return;
  }
  const state = crypto.randomBytes(16).toString("hex");
  registerOAuthState(state);
  const url = generateAuthUrl(state);
  res.json({ ok: true, url, state });
});

router.get("/google/oauth/start", (_req: Request, res: Response) => {
  if (!isGoogleConfigured()) {
    res.status(503).json({ ok: false, error: "Google OAuth not configured" });
    return;
  }
  const state = crypto.randomBytes(16).toString("hex");
  registerOAuthState(state);
  const url = generateAuthUrl(state);
  res.json({ ok: true, url, state });
});

router.get("/google/status", async (_req: Request, res: Response) => {
  try {
    const status = await getGBPStatus(ORG_ID);
    res.json(status);
  } catch (e) {
    res.status(500).json({ ok: false, error: "Failed to get GBP status" });
  }
});

router.get("/google/accounts", async (_req: Request, res: Response) => {
  const client = await pool.connect();
  try {
    const acc = await client.query(`SELECT access_token FROM google_accounts WHERE org_id=$1 LIMIT 1`, [ORG_ID]);
    if (acc.rows.length === 0) {
      res.status(401).json({ ok: false, error: "Google account not connected" });
      return;
    }
    const accounts = await getAccounts((acc.rows[0] as { access_token: string }).access_token);
    res.json({ ok: true, accounts });
  } catch (e) {
    res.status(500).json({ error: "Failed to get accounts" });
  } finally {
    client.release();
  }
});

router.get("/google/locations", async (_req: Request, res: Response) => {
  const client = await pool.connect();
  try {
    const rows = await client.query(
      `SELECT id, name, primary_category, rating, reviews_count, phone, website, lat, lng, last_sync_at FROM google_locations WHERE org_id=$1 ORDER BY name`,
      [ORG_ID]
    );
    res.json({ ok: true, locations: rows.rows });
  } catch (e) {
    res.status(500).json({ error: "Failed to get locations" });
  } finally {
    client.release();
  }
});

router.get("/google/reviews/:locationId", async (req: Request, res: Response) => {
  const { locationId } = req.params;
  const client = await pool.connect();
  try {
    const rows = await client.query(
      `SELECT id, reviewer_name, reviewer_photo, rating, comment, create_time, update_time, reply_comment, reply_updated_at
       FROM google_reviews WHERE org_id=$1 AND location_id=$2 ORDER BY create_time DESC LIMIT 50`,
      [ORG_ID, locationId]
    );
    res.json({ ok: true, reviews: rows.rows });
  } catch (e) {
    res.status(500).json({ error: "Failed to get reviews" });
  } finally {
    client.release();
  }
});

router.get("/google/reviews", async (_req: Request, res: Response) => {
  const client = await pool.connect();
  try {
    const rows = await client.query(
      `SELECT id, location_id, reviewer_name, reviewer_photo, rating, comment, create_time, update_time, reply_comment
       FROM google_reviews WHERE org_id=$1 ORDER BY create_time DESC LIMIT 50`,
      [ORG_ID]
    );
    res.json({ ok: true, reviews: rows.rows });
  } catch (e) {
    res.status(500).json({ error: "Failed to get reviews" });
  } finally {
    client.release();
  }
});

router.post("/google/sync", async (_req: Request, res: Response) => {
  try {
    store.broadcast({ type: "gbp:sync_started" });
    const result = await syncAll(ORG_ID);
    store.broadcast({ type: "gbp:sync_complete", ...result });
    res.json({ ok: true, ...result });
  } catch (e) {
    logger.error({ e }, "[GBP] Manual sync failed");
    res.status(500).json({ ok: false, error: "Sync failed" });
  }
});

router.post("/google/disconnect", async (_req: Request, res: Response) => {
  const client = await pool.connect();
  try {
    await client.query(`DELETE FROM google_accounts WHERE org_id=$1`, [ORG_ID]);
    store.logActivity({ type: "team", label: "Google Business Profile déconnecté", targetType: "connector" });
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: "Failed to disconnect" });
  } finally {
    client.release();
  }
});

router.get("/google/performance", async (req: Request, res: Response) => {
  const { locationId } = req.query as { locationId?: string };
  const accessToken = await getValidToken(ORG_ID);
  if (!accessToken) { res.status(401).json({ ok: false, error: "Google account not connected" }); return; }
  try {
    const client = await pool.connect();
    let locationName = locationId ?? "";
    if (!locationName) {
      const locs = await client.query(`SELECT raw_data FROM google_locations WHERE org_id=$1 LIMIT 1`, [ORG_ID]);
      client.release();
      if (locs.rows.length === 0) { res.json({ ok: true, metrics: [], summary: {} }); return; }
      const raw = locs.rows[0].raw_data as { name?: string };
      locationName = raw?.name ?? "";
    } else {
      client.release();
    }
    if (!locationName) { res.json({ ok: true, metrics: [], summary: {} }); return; }

    const metrics = await getPerformance(accessToken, locationName);

    const summary: Record<string, number> = {};
    for (const serie of metrics as Array<{ dailyMetric?: string; timeSeries?: { datedValues?: Array<{ value?: number }> } }>) {
      const key = serie.dailyMetric ?? "UNKNOWN";
      const total = (serie.timeSeries?.datedValues ?? []).reduce((s, v) => s + (v.value ?? 0), 0);
      summary[key] = total;
    }

    res.json({ ok: true, locationName, metrics, summary });
  } catch (e) {
    logger.error({ e }, "[GBP] performance route failed");
    res.status(500).json({ ok: false, error: "Failed to fetch performance data" });
  }
});

router.post("/google/post", async (req: Request, res: Response) => {
  const { locationId, text, callToActionType, callToActionUrl } = req.body as {
    locationId?: string; text?: string; callToActionType?: string; callToActionUrl?: string;
  };
  if (!text?.trim()) { res.status(400).json({ ok: false, error: "text is required" }); return; }

  const accessToken = await getValidToken(ORG_ID);
  if (!accessToken) { res.status(401).json({ ok: false, error: "Google account not connected" }); return; }

  let locationName = locationId ?? "";
  if (!locationName) {
    const client = await pool.connect();
    try {
      const locs = await client.query(`SELECT raw_data FROM google_locations WHERE org_id=$1 LIMIT 1`, [ORG_ID]);
      if (locs.rows.length > 0) {
        const raw = locs.rows[0].raw_data as { name?: string };
        locationName = raw?.name ?? "";
      }
    } finally { client.release(); }
  }
  if (!locationName) { res.status(400).json({ ok: false, error: "No location found. Sync GBP first." }); return; }

  const result = await publishGBPPost(accessToken, locationName, text, callToActionType, callToActionUrl);
  if (result.ok) {
    store.logActivity({ type: "ai", label: `Post GBP publié : "${text.slice(0, 60)}…"`, targetType: "google_business" });
  }
  res.json(result);
});

router.post("/google/reply", async (req: Request, res: Response) => {
  const { reviewId, locationId, comment, useAI } = req.body as {
    reviewId?: string; locationId?: string; comment?: string; useAI?: boolean;
  };
  if (!reviewId) { res.status(400).json({ ok: false, error: "reviewId is required" }); return; }

  const accessToken = await getValidToken(ORG_ID);
  if (!accessToken) { res.status(401).json({ ok: false, error: "Google account not connected" }); return; }

  const client = await pool.connect();
  let finalComment = comment ?? "";
  try {
    if (useAI || !finalComment) {
      const rev = await client.query(
        `SELECT reviewer_name, rating, comment FROM google_reviews WHERE review_id=$1 AND org_id=$2 LIMIT 1`,
        [reviewId, ORG_ID],
      );
      if (rev.rows.length > 0) {
        const row = rev.rows[0] as { reviewer_name: string; rating: number; comment: string };
        finalComment = await generateAIReply(row.reviewer_name, row.rating, row.comment);
      }
    }
    if (!finalComment) { res.status(400).json({ ok: false, error: "comment is required" }); return; }

    let locationName = locationId ?? "";
    if (!locationName) {
      const locs = await client.query(`SELECT raw_data FROM google_locations WHERE org_id=$1 LIMIT 1`, [ORG_ID]);
      if (locs.rows.length > 0) {
        const raw = locs.rows[0].raw_data as { name?: string };
        locationName = raw?.name ?? "";
      }
    }
    if (!locationName) { res.status(400).json({ ok: false, error: "No location found" }); return; }

    const result = await replyToReview(accessToken, locationName, reviewId, finalComment);

    if (result.ok) {
      await client.query(
        `UPDATE google_reviews SET reply_comment=$1, reply_updated_at=now() WHERE review_id=$2 AND org_id=$3`,
        [finalComment, reviewId, ORG_ID],
      );
      store.logActivity({ type: "team", label: `Réponse GBP publiée — avis ${reviewId}`, targetType: "google_business" });
    }
    res.json({ ok: result.ok, reply: finalComment, error: result.error });
  } finally {
    client.release();
  }
});

router.post("/google/ai-reply-preview", async (req: Request, res: Response) => {
  const { reviewId } = req.body as { reviewId?: string };
  if (!reviewId) { res.status(400).json({ ok: false, error: "reviewId required" }); return; }
  const client = await pool.connect();
  try {
    const rev = await client.query(
      `SELECT reviewer_name, rating, comment FROM google_reviews WHERE review_id=$1 AND org_id=$2 LIMIT 1`,
      [reviewId, ORG_ID],
    );
    if (rev.rows.length === 0) { res.status(404).json({ ok: false, error: "Review not found" }); return; }
    const row = rev.rows[0] as { reviewer_name: string; rating: number; comment: string };
    const reply = await generateAIReply(row.reviewer_name, row.rating, row.comment);
    res.json({ ok: true, reply });
  } finally {
    client.release();
  }
});

export default router;
