import { Router } from "express";
import { db, notificationsTable } from "@workspace/db";
import { eq, desc } from "drizzle-orm";
import { isDemoMode } from "../services/mock-data.js";

const router = Router();

const SEED: Array<typeof notificationsTable.$inferInsert> = [
  { id: "notif1", type: "warning", title: "Monitor en alerte", message: "Boulangerie Martin — temps de réponse > 3s", read: false },
  { id: "notif2", type: "success", title: "Audit terminé", message: "monagence.fr — Score 82/100 (+7 pts)", read: false },
  { id: "notif3", type: "info", title: "Rapport envoyé", message: "Rapport Mai 2026 envoyé à Restaurant Le Soleil", read: true },
  { id: "notif4", type: "error", title: "Monitor DOWN", message: "Coiffeur Lyon — indisponible depuis 12 min", read: false },
  { id: "notif5", type: "info", title: "Nouveau membre", message: "Sophie Martin a rejoint le workspace", read: true },
  { id: "notif6", type: "warning", title: "Limite d'usage", message: "Audits : 87/100 utilisés ce mois-ci", read: false },
];

async function ensureSeed() {
  if (!isDemoMode()) return; // production: notifications are generated by real events only
  const existing = await db.select().from(notificationsTable).limit(1);
  if (existing.length === 0) {
    await db.insert(notificationsTable).values(SEED).onConflictDoNothing();
  }
}

router.get("/notifications", async (_req, res) => {
  try {
    await ensureSeed();
    const notifs = await db.select().from(notificationsTable).orderBy(desc(notificationsTable.createdAt)).limit(50);
    res.json(notifs);
  } catch (e) {
    res.status(500).json({ error: "Failed to fetch notifications" });
  }
});

router.post("/notifications", async (req, res) => {
  const { type = "info", title, message, link } = req.body as Partial<typeof notificationsTable.$inferInsert>;
  if (!title || !message) { res.status(400).json({ error: "title and message required" }); return; }
  try {
    const [notif] = await db.insert(notificationsTable).values({
      id: "notif" + Date.now(),
      type: type || "info", title, message, link: link || null, read: false,
    }).returning();
    res.status(201).json(notif);
  } catch (e) {
    res.status(500).json({ error: "Failed to create notification" });
  }
});

router.patch("/notifications/:id/read", async (req, res) => {
  try {
    const [notif] = await db.update(notificationsTable).set({ read: true }).where(eq(notificationsTable.id, req.params.id)).returning();
    res.json(notif || { ok: true });
  } catch (e) {
    res.status(500).json({ error: "Failed to mark read" });
  }
});

router.patch("/notifications/read-all", async (_req, res) => {
  try {
    await db.update(notificationsTable).set({ read: true });
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: "Failed to mark all read" });
  }
});

router.delete("/notifications/:id", async (req, res) => {
  await db.delete(notificationsTable).where(eq(notificationsTable.id, req.params.id));
  res.json({ ok: true });
});

export default router;
